// DDC/CI frame codec shared by every transport (VIA USB bridge, /dev/i2c-N, mock).
//
// Wire format (MCCS / DDC/CI, 08 §3.1-3.3, 07 §4.7, 06 §5.2):
//   host -> display : 6E 51 (80|n) payload[n] chk      chk = 6E ^ 51 ^ (80|n) ^ payload...
//   display -> host : 6E (80|L) payload[L] chk          0x50 ^ 6E ^ (80|L) ^ payload ^ chk == 0
// The destination byte 0x6E is the I2C write address of slave 0x37; it is part of the checksum
// but transports send it differently (VIA: first byte of the control-transfer data stage;
// i2c-dev: generated by the kernel from ioctl(I2C_SLAVE, 0x37)). `buildDdcMessage` therefore
// returns the frame WITHOUT 0x6E, as required by DdcTransport.write() (types.ts).

import type { VcpValue } from '../types.ts';
import { DdcError } from './errors.ts';

/** 7-bit I2C address of the DDC/CI slave in the display (8-bit 0x6E write / 0x6F read). */
export const DDC_CI_SLAVE = 0x37;
/** 7-bit I2C address of the EDID EEPROM (E-DDC). */
export const EDID_SLAVE = 0x50;
/** Destination byte of host->display frames (0x37 << 1). */
export const DDC_DEST = 0x6e;
/** Read address byte (0x37 << 1 | 1); the VIA bridge takes it as wIndex (08 §4.2). */
export const DDC_READ_ADDR = 0x6f;
/** Source byte of host frames. */
export const DDC_HOST_SRC = 0x51;
/** Virtual host address that seeds the reply checksum (08 §3.2). */
export const DDC_REPLY_SEED = 0x50;

export const OP_GET_VCP = 0x01;
export const OP_GET_VCP_REPLY = 0x02;
export const OP_SET_VCP = 0x03;
export const OP_CAPS_REQUEST = 0xf3;
export const OP_CAPS_REPLY = 0xe3;

/** TPV/Philips extended VCP prefix: the 3-byte VCP code E2 A0 xx (06 §6.2). */
const EXT_PREFIX = [0xe2, 0xa0] as const;
export const EXT_BASE = 0xe2a000;

/** Largest payload the codec accepts in one frame (MCCS limit). */
const MAX_PAYLOAD = 32;

/** VCP code used by the USB-DDC / DDC-CI support probe (colour preset, 08 §3.6, 07 §4.8.1). */
export const PROBE_VCP = 0x14;
/** MCCS "display controller type": the low byte identifies the scaler vendor (08 §3.4). */
export const VCP_CONTROLLER_TYPE = 0xc8;
/** Input source; its low byte is part of the capability cache key (06 §4.8). */
export const VCP_INPUT_SOURCE = 0x60;
/** Display firmware level; used for the cache key only when max == 201 (07 §8.4-I). */
export const VCP_FIRMWARE_LEVEL = 0xc9;

// ───────────────────────────── checksum / frames ─────────────────────────────

/** XOR of `bytes` starting from `seed`. */
export function xorChecksum(bytes: ArrayLike<number>, seed = 0): number {
  let x = seed & 0xff;
  for (let i = 0; i < bytes.length; i++) x ^= bytes[i] & 0xff;
  return x;
}

function assertByte(v: number, what: string): void {
  if (!Number.isInteger(v) || v < 0 || v > 0xff) throw new DdcError('argument', `${what} must be a byte, got ${v}`);
}

function assertWord(v: number, what: string): void {
  if (!Number.isInteger(v) || v < 0 || v > 0xffff) throw new DdcError('argument', `${what} must be 0..65535, got ${v}`);
}

/**
 * Host->display frame without the destination byte: `51 (80|n) payload chk` (08 §3.1).
 * The checksum includes the implicit destination 0x6E, exactly like Interface2.imethod_4 and
 * DDCHelper's `(0x80|n) ^ 0x3F ^ payload...` (0x3F = 0x6E ^ 0x51, 07 §4.7).
 */
export function buildDdcMessage(payload: ArrayLike<number>): Uint8Array {
  const n = payload.length;
  if (n < 1 || n > MAX_PAYLOAD) throw new DdcError('argument', `DDC/CI payload length ${n} out of range 1..${MAX_PAYLOAD}`);
  const out = new Uint8Array(n + 3);
  out[0] = DDC_HOST_SRC;
  out[1] = 0x80 | n;
  for (let i = 0; i < n; i++) {
    assertByte(payload[i], 'payload byte');
    out[2 + i] = payload[i];
  }
  out[n + 2] = xorChecksum(out.subarray(0, n + 2), DDC_DEST);
  return out;
}

/** The complete on-the-wire frame including the destination byte (what the VIA bridge sends). */
export function toWireFrame(message: Uint8Array): Uint8Array {
  const out = new Uint8Array(message.length + 1);
  out[0] = DDC_DEST;
  out.set(message, 1);
  return out;
}

// ───────────────────────────── request payloads ─────────────────────────────

export function getVcpPayload(code: number): number[] {
  assertByte(code, 'VCP code');
  return [OP_GET_VCP, code];
}

export function setVcpPayload(code: number, value: number): number[] {
  assertByte(code, 'VCP code');
  assertWord(value, 'VCP value');
  return [OP_SET_VCP, code, value >> 8, value & 0xff];
}

/** Extended get `01 E2 A0 xx` (08 §3.3, 07 §4.8.3). */
export function getExtPayload(sub: number): number[] {
  assertByte(sub, 'extended VCP sub-code');
  return [OP_GET_VCP, EXT_PREFIX[0], EXT_PREFIX[1], sub];
}

/** Extended set `03 E2 A0 xx hi lo`. */
export function setExtPayload(sub: number, value: number): number[] {
  assertByte(sub, 'extended VCP sub-code');
  assertWord(value, 'VCP value');
  return [OP_SET_VCP, EXT_PREFIX[0], EXT_PREFIX[1], sub, value >> 8, value & 0xff];
}

/** Capabilities request `F3 offH offL` (08 §3.5). */
export function capsRequestPayload(offset: number): number[] {
  assertWord(offset, 'capabilities offset');
  return [OP_CAPS_REQUEST, offset >> 8, offset & 0xff];
}

/** Raw vendor get: opcode 0x01 followed by up to 27 command bytes (Interface2.GetDDC, 08 §3.3). */
export function rawGetPayload(args: ArrayLike<number>): number[] {
  if (args.length < 1 || args.length > 27) throw new DdcError('argument', `raw query length ${args.length} out of range 1..27`);
  const out = [OP_GET_VCP];
  for (let i = 0; i < args.length; i++) {
    assertByte(args[i], 'raw query byte');
    out.push(args[i]);
  }
  return out;
}

// ───────────────────────────── extended code helpers ─────────────────────────────

/** True for the 3-byte TPV codes 0xE2A000..0xE2A0FF used as enum values in the vendor model. */
export function isExtCode(code: number): boolean {
  return Number.isInteger(code) && code >= EXT_BASE && code <= EXT_BASE + 0xff;
}

export function extCode(sub: number): number {
  assertByte(sub, 'extended VCP sub-code');
  return EXT_BASE | sub;
}

export function extSub(code: number): number {
  if (!isExtCode(code)) throw new DdcError('argument', `0x${code.toString(16)} is not an E2A0xx code`);
  return code & 0xff;
}

export function hex2(v: number): string {
  return (v & 0xff).toString(16).toUpperCase().padStart(2, '0');
}

export function hexBytes(bytes: ArrayLike<number>): string {
  const parts: string[] = [];
  for (let i = 0; i < bytes.length; i++) parts.push(hex2(bytes[i]));
  return parts.join(' ');
}

// ───────────────────────────── reply validation / parsing ─────────────────────────────

export type ReplyCheck = { ok: true; length: number } | { ok: false; reason: string };

/**
 * Validate a raw reply buffer as read from the bus (starts with the display's source byte).
 * Rules from GetStandardData (08 §3.2): L = r[1]-0x80 > 0, L+3 <= buffer length, and
 * 0x50 ^ r[0] ^ ... ^ r[L+2] == 0. We additionally require r[0] == 0x6E up front, which the vendor
 * checks one step later (Interface2.imethod_7 / GetStandardDDC) — rejecting it here makes the
 * attempt retryable instead of failing the operation.
 * A DDC/CI null message (6E 80 BE, L == 0) is invalid here, so callers retry (display busy).
 */
export function checkReply(raw: Uint8Array): ReplyCheck {
  if (raw.length < 3) return { ok: false, reason: `short reply (${raw.length} bytes)` };
  if (raw[0] !== DDC_DEST) return { ok: false, reason: `bad source byte 0x${hex2(raw[0])}` };
  if (raw[1] < 0x80) return { ok: false, reason: `bad length byte 0x${hex2(raw[1])}` };
  const len = raw[1] - 0x80;
  if (len === 0) return { ok: false, reason: 'null message' };
  if (len + 3 > raw.length) return { ok: false, reason: `length ${len} exceeds buffer ${raw.length}` };
  if (xorChecksum(raw.subarray(0, len + 3), DDC_REPLY_SEED) !== 0) return { ok: false, reason: 'checksum mismatch' };
  return { ok: true, length: len };
}

export function isNullMessage(raw: Uint8Array): boolean {
  return raw.length >= 3 && raw[0] === DDC_DEST && raw[1] === 0x80 && raw[2] === (DDC_REPLY_SEED ^ DDC_DEST ^ 0x80);
}

/** Payload bytes (after the length byte, without checksum) of a validated reply. */
export function replyPayload(raw: Uint8Array): Uint8Array {
  const check = checkReply(raw);
  if (!check.ok) throw new DdcError('invalid-reply', check.reason);
  return raw.slice(2, 2 + check.length);
}

/**
 * VCP get reply (standard `02 RC cc TP MH ML SH SL` or extended). Parsing is length-relative like the
 * hub (Interface2.GetStandardDDC, 08 §3.3): value = r[L]:r[L+1], max = r[L-2]:r[L-1], i.e. always the
 * last four payload bytes. For L == 8 this equals DDCHelper's fixed payload[4..7] (07 §4.8.3).
 * The result code is reported but, like the vendor hub path, not treated as an error.
 */
export function parseVcpReply(raw: Uint8Array): VcpValue {
  const check = checkReply(raw);
  if (!check.ok) throw new DdcError('invalid-reply', check.reason);
  const len = check.length;
  if (len < 4 || len > 30) throw new DdcError('invalid-reply', `VCP reply length ${len} out of range 4..30`);
  return {
    value: (raw[len] << 8) | raw[len + 1],
    max: (raw[len - 2] << 8) | raw[len - 1],
    resultCode: raw[3],
  };
}

/** Opcode and echoed VCP code of a standard 8-byte reply, or null for any other layout. */
export function standardReplyEcho(raw: Uint8Array): { opcode: number; code: number } | null {
  if (raw.length < 11 || raw[1] !== 0x88) return null;
  return { opcode: raw[2], code: raw[4] };
}

/** One capabilities fragment: `E3 offH offL data...` (08 §3.5). NUL bytes are dropped like Util.smethod_8. */
export interface CapsFragment {
  offset: number;
  /** Fragment data length as sent (L-3), before NUL stripping — this is what the offset advances by. */
  length: number;
  text: string;
}

export function parseCapsFragment(raw: Uint8Array): CapsFragment {
  const payload = replyPayload(raw);
  if (payload[0] !== OP_CAPS_REPLY) throw new DdcError('invalid-reply', `capabilities reply opcode 0x${hex2(payload[0])}`);
  if (payload.length < 3) throw new DdcError('invalid-reply', `capabilities reply too short (${payload.length})`);
  const data = payload.subarray(3);
  let text = '';
  for (const b of data) if (b !== 0) text += asciiChar(b);
  return { offset: (payload[1] << 8) | payload[2], length: data.length, text };
}

/** .NET Encoding.ASCII.GetChars: bytes above 0x7F decode to '?'. */
function asciiChar(b: number): string {
  return b > 0x7f ? '?' : String.fromCharCode(b);
}

// ───────────────────────────── TPV "FE" identity page (08 §3.4) ─────────────────────────────

/** Command bytes that follow opcode 0x01 for each TPV identity query (Interface8/Interface2/Interface7). */
export const TPV_QUERY = {
  /** `6E 51 86 01 FE E9 0D 00 00 A2` → ASCII, e.g. "34M2C8600". */
  modelName: [0xfe, 0xe9, 0x0d, 0x00, 0x00],
  /** `6E 51 86 01 FE E1 E6 1D 00 5C` → ASCII BOM, e.g. "100GPRS2003NA1SXXY". */
  bomString: [0xfe, 0xe1, 0xe6, 0x1d, 0x00],
  /** `6E 51 86 01 FE E1 E6 06 00 47` → ASCII, e.g. "V1.01". */
  fwVersion: [0xfe, 0xe1, 0xe6, 0x06, 0x00],
  /** `6E 51 86 01 FE E1 A1 01 00 07` → sub[1]:sub[2] (NTK: sub[2]). */
  dualImageBank: [0xfe, 0xe1, 0xa1, 0x01, 0x00],
  /** `6E 51 86 01 FE E1 A1 01 01 06` → sub[1..4] big-endian (Realtek scalers). */
  bootFlagAddress: [0xfe, 0xe1, 0xa1, 0x01, 0x01],
  /** `6E 51 86 01 FE E1 E8 00 00 4F` → ASCII, e.g. "RTD2738VL". */
  scalerName: [0xfe, 0xe1, 0xe8, 0x00, 0x00],
  /** `6E 51 86 01 FE E1 A7 07 00 07` → ASCII. */
  panelName: [0xfe, 0xe1, 0xa7, 0x07, 0x00],
  /** `6E 51 86 01 FE EF 13 00 20 9A` → raw ASCII serial (hub variant, Interface2.GetSN). */
  serialNumber: [0xfe, 0xef, 0x13, 0x00, 0x20],
} as const;

/**
 * Interface2.imethod_8 (08 §3.4): payload of a TPV reply. The result has length L; data starts at
 * r[5], or r[6] when r[5] == 0 (pad byte), and L-(start-2) bytes are copied; the rest stays zero.
 * Bytes r[2..4] are an echo/opcode the vendor never inspects.
 */
export function extractTpvPayload(raw: Uint8Array): Uint8Array {
  const check = checkReply(raw);
  if (!check.ok) throw new DdcError('invalid-reply', check.reason);
  const len = check.length;
  const start = raw[5] === 0 ? 6 : 5;
  const count = len - (start - 2);
  if (count < 0) throw new DdcError('invalid-reply', `TPV reply length ${len} too short`);
  const out = new Uint8Array(len);
  out.set(raw.subarray(start, start + count));
  return out;
}

/** Interface2.esewYiSlRh: ASCII of the TPV payload up to the first NUL (Util.smethod_5). */
export function tpvAscii(raw: Uint8Array): string {
  const sub = extractTpvPayload(raw);
  let s = '';
  for (const b of sub) {
    if (b === 0) break;
    s += asciiChar(b);
  }
  return s;
}

/**
 * Factory serial number (Interface2.GetSN, 08 §3.4; 07 §3.4.3): the reply payload is the raw ASCII
 * serial with no opcode. N = L (or L-2 when L == 32); SN = ascii(r[2..N+2)) without NULs; empty when
 * N < 13; truncated to 14 characters when N >= 14. (The vendor's Substring throws when N >= 14 but the
 * string is shorter; we just keep the shorter string.)
 */
export function parseSerialReply(raw: Uint8Array): string {
  const check = checkReply(raw);
  if (!check.ok) throw new DdcError('invalid-reply', check.reason);
  const n = check.length === 32 ? 30 : check.length;
  let sn = '';
  for (const b of raw.subarray(2, 2 + n)) if (b !== 0) sn += asciiChar(b);
  if (n < 13) return '';
  return n >= 14 ? sn.slice(0, 14) : sn;
}

export type ScalerType = 'RTK' | 'MTK' | 'NTK' | 'HVW' | 'Unknown';

/** VCP C8 low byte → scaler family (Interface8.GetScalerIC; same numbers as DeviceData.ScalerType). */
export function scalerTypeOf(scalerIc: number): ScalerType {
  switch (scalerIc) {
    case 0x09: return 'RTK';
    case 0x05: return 'MTK';
    case 0x12: return 'NTK';
    case 0x24: return 'HVW';
    default: return 'Unknown';
  }
}

/**
 * GetScalerIC (ML/Interface8.cs:257-287): sub = r[5 .. 5+L), ScalerIC = sub[4] = r[9], the SL byte of
 * the standard reply `02 RC C8 TP MH ML SH SL` (L = 8). The vendor throws (scaler Unknown) only for
 * L < 5; for L = 5..7 it reads the checksum or the padding behind the reply, which could classify a
 * truncated reply as a known scaler family (a padding byte of 0x09 reads as RTK). The port requires
 * r[9] to be a payload byte, i.e. L >= 8.
 */
export function parseScalerIc(raw: Uint8Array): number {
  const check = checkReply(raw);
  if (!check.ok) throw new DdcError('invalid-reply', check.reason);
  if (check.length < 8) throw new DdcError('invalid-reply', `scaler IC reply length ${check.length} < 8 (no SL byte)`);
  return raw[9];
}

/** GetDualImage: (sub[1] << 8) | sub[2], or sub[2] for Novatek scalers. */
export function parseDualImageBank(raw: Uint8Array, scaler: ScalerType): number {
  const sub = extractTpvPayload(raw);
  if (sub.length < 3) throw new DdcError('invalid-reply', 'dual image bank reply too short');
  return scaler === 'NTK' ? sub[2] : (sub[1] << 8) | sub[2];
}

/** Interface7.GetBootFlagAddress: sub[1..4] big-endian. */
export function parseBootFlagAddress(raw: Uint8Array): number {
  const sub = extractTpvPayload(raw);
  if (sub.length < 5) throw new DdcError('invalid-reply', 'boot flag address reply too short');
  return ((sub[1] << 24) | (sub[2] << 16) | (sub[3] << 8) | sub[4]) >>> 0;
}

/** Brand rule for the BOM string (Interface8.imethod_13): PHILIPS needs sub[4]=='P' or the one literal. */
export type BomBrand = 'PHILIPS' | 'AOC';
const PHILIPS_BOM_EXCEPTION = '100GARVGG88NT1SXXY';

export function parseBomString(raw: Uint8Array, brands: readonly BomBrand[] = ['PHILIPS']): string {
  const sub = extractTpvPayload(raw);
  const text = tpvAscii(raw);
  const fifth = sub.length > 4 ? sub[4] : -1;
  const ok =
    (brands.includes('PHILIPS') && (fifth === 0x50 || text === PHILIPS_BOM_EXCEPTION)) ||
    (brands.includes('AOC') && fifth === 0x41);
  if (!ok) throw new DdcError('unsupported', `BOM string "${text}" not accepted for ${brands.join('/')}`);
  return text;
}

/**
 * Firmware version from VCP C9 (Display.method_1, 07 §8.4-I): used only when max == 201;
 * "V<hi>.<lo:D2>", "" when the value is zero. Returns null when C9 is not usable.
 */
export function fwVersionFromC9(v: VcpValue): string | null {
  if (v.max !== 201) return null;
  const hi = (v.value >> 8) & 0xff;
  const lo = v.value & 0xff;
  if (hi === 0 && lo === 0) return '';
  return `V${hi}.${String(lo).padStart(2, '0')}`;
}
